//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "12.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class CustomerTypes {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal CustomerTypes() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.CustomerTypes", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Retail Customer.
        /// </summary>
        internal static string CustomerType_01 {
            get {
                return ResourceManager.GetString("CustomerType_01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preferred Customer.
        /// </summary>
        internal static string CustomerType_02 {
            get {
                return ResourceManager.GetString("CustomerType_02", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Distributor.
        /// </summary>
        internal static string CustomerType_03 {
            get {
                return ResourceManager.GetString("CustomerType_03", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Brand Ambassador.
        /// </summary>
        internal static string CustomerType_04 {
            get {
                return ResourceManager.GetString("CustomerType_04", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IL Distributor.
        /// </summary>
        internal static string CustomerType_05 {
            get {
                return ResourceManager.GetString("CustomerType_05", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Employee.
        /// </summary>
        internal static string CustomerType_06 {
            get {
                return ResourceManager.GetString("CustomerType_06", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reserved WebAlias.
        /// </summary>
        internal static string CustomerType_07 {
            get {
                return ResourceManager.GetString("CustomerType_07", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AU Distributor.
        /// </summary>
        internal static string CustomerType_08 {
            get {
                return ResourceManager.GetString("CustomerType_08", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CA Distributor.
        /// </summary>
        internal static string CustomerType_09 {
            get {
                return ResourceManager.GetString("CustomerType_09", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SG Distributor.
        /// </summary>
        internal static string CustomerType_10 {
            get {
                return ResourceManager.GetString("CustomerType_10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Party Host.
        /// </summary>
        internal static string CustomerType_11 {
            get {
                return ResourceManager.GetString("CustomerType_11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prospect Or Lead.
        /// </summary>
        internal static string CustomerType_12 {
            get {
                return ResourceManager.GetString("CustomerType_12", resourceCulture);
            }
        }
    }
}
