//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "12.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class CustomerStatuses {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal CustomerStatuses() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.CustomerStatuses", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deleted.
        /// </summary>
        internal static string CustomerStatus_00 {
            get {
                return ResourceManager.GetString("CustomerStatus_00", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Active.
        /// </summary>
        internal static string CustomerStatus_01 {
            get {
                return ResourceManager.GetString("CustomerStatus_01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inactive.
        /// </summary>
        internal static string CustomerStatus_02 {
            get {
                return ResourceManager.GetString("CustomerStatus_02", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pending.
        /// </summary>
        internal static string CustomerStatus_03 {
            get {
                return ResourceManager.GetString("CustomerStatus_03", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cart Abandoned.
        /// </summary>
        internal static string CustomerStatus_04 {
            get {
                return ResourceManager.GetString("CustomerStatus_04", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open Party.
        /// </summary>
        internal static string CustomerStatus_05 {
            get {
                return ResourceManager.GetString("CustomerStatus_05", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Closed Party.
        /// </summary>
        internal static string CustomerStatus_06 {
            get {
                return ResourceManager.GetString("CustomerStatus_06", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancelled Party.
        /// </summary>
        internal static string CustomerStatus_07 {
            get {
                return ResourceManager.GetString("CustomerStatus_07", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancelled.
        /// </summary>
        internal static string CustomerStatus_08 {
            get {
                return ResourceManager.GetString("CustomerStatus_08", resourceCulture);
            }
        }
    }
}
