//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "12.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class FrequencyTypes {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal FrequencyTypes() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.FrequencyTypes", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weekly.
        /// </summary>
        internal static string FrequencyType_01 {
            get {
                return ResourceManager.GetString("FrequencyType_01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Every two weeks.
        /// </summary>
        internal static string FrequencyType_02 {
            get {
                return ResourceManager.GetString("FrequencyType_02", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Monthly.
        /// </summary>
        internal static string FrequencyType_03 {
            get {
                return ResourceManager.GetString("FrequencyType_03", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quarterly.
        /// </summary>
        internal static string FrequencyType_04 {
            get {
                return ResourceManager.GetString("FrequencyType_04", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Twice a year.
        /// </summary>
        internal static string FrequencyType_05 {
            get {
                return ResourceManager.GetString("FrequencyType_05", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yearly.
        /// </summary>
        internal static string FrequencyType_06 {
            get {
                return ResourceManager.GetString("FrequencyType_06", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bi-monthly.
        /// </summary>
        internal static string FrequencyType_07 {
            get {
                return ResourceManager.GetString("FrequencyType_07", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Every 4 weeks.
        /// </summary>
        internal static string FrequencyType_08 {
            get {
                return ResourceManager.GetString("FrequencyType_08", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Every 6 weeks.
        /// </summary>
        internal static string FrequencyType_09 {
            get {
                return ResourceManager.GetString("FrequencyType_09", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Every 8 weeks.
        /// </summary>
        internal static string FrequencyType_10 {
            get {
                return ResourceManager.GetString("FrequencyType_10", resourceCulture);
            }
        }
    }
}
