//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "12.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Languages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Languages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.Languages", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English.
        /// </summary>
        internal static string LanguageID_000 {
            get {
                return ResourceManager.GetString("LanguageID_000", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spanish.
        /// </summary>
        internal static string LanguageID_001 {
            get {
                return ResourceManager.GetString("LanguageID_001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to German.
        /// </summary>
        internal static string LanguageID_002 {
            get {
                return ResourceManager.GetString("LanguageID_002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Korean.
        /// </summary>
        internal static string LanguageID_003 {
            get {
                return ResourceManager.GetString("LanguageID_003", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Belorussian.
        /// </summary>
        internal static string LanguageID_004 {
            get {
                return ResourceManager.GetString("LanguageID_004", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Japanese.
        /// </summary>
        internal static string LanguageID_005 {
            get {
                return ResourceManager.GetString("LanguageID_005", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to French.
        /// </summary>
        internal static string LanguageID_006 {
            get {
                return ResourceManager.GetString("LanguageID_006", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mandarin.
        /// </summary>
        internal static string LanguageID_007 {
            get {
                return ResourceManager.GetString("LanguageID_007", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chinese (Taiwan).
        /// </summary>
        internal static string LanguageID_008 {
            get {
                return ResourceManager.GetString("LanguageID_008", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thai.
        /// </summary>
        internal static string LanguageID_009 {
            get {
                return ResourceManager.GetString("LanguageID_009", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tagalec (Phillipino).
        /// </summary>
        internal static string LanguageID_010 {
            get {
                return ResourceManager.GetString("LanguageID_010", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hungarian.
        /// </summary>
        internal static string LanguageID_011 {
            get {
                return ResourceManager.GetString("LanguageID_011", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finnish.
        /// </summary>
        internal static string LanguageID_012 {
            get {
                return ResourceManager.GetString("LanguageID_012", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Norsk.
        /// </summary>
        internal static string LanguageID_013 {
            get {
                return ResourceManager.GetString("LanguageID_013", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Indonesian.
        /// </summary>
        internal static string LanguageID_015 {
            get {
                return ResourceManager.GetString("LanguageID_015", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Portuguese.
        /// </summary>
        internal static string LanguageID_016 {
            get {
                return ResourceManager.GetString("LanguageID_016", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Italian.
        /// </summary>
        internal static string LanguageID_017 {
            get {
                return ResourceManager.GetString("LanguageID_017", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dutch.
        /// </summary>
        internal static string LanguageID_018 {
            get {
                return ResourceManager.GetString("LanguageID_018", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Russian.
        /// </summary>
        internal static string LanguageID_019 {
            get {
                return ResourceManager.GetString("LanguageID_019", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Slovakia.
        /// </summary>
        internal static string LanguageID_020 {
            get {
                return ResourceManager.GetString("LanguageID_020", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cyrillic.
        /// </summary>
        internal static string LanguageID_021 {
            get {
                return ResourceManager.GetString("LanguageID_021", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Estonian.
        /// </summary>
        internal static string LanguageID_022 {
            get {
                return ResourceManager.GetString("LanguageID_022", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English (Malaysia).
        /// </summary>
        internal static string LanguageID_080 {
            get {
                return ResourceManager.GetString("LanguageID_080", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chinese (Malaysia).
        /// </summary>
        internal static string LanguageID_081 {
            get {
                return ResourceManager.GetString("LanguageID_081", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Malay.
        /// </summary>
        internal static string LanguageID_082 {
            get {
                return ResourceManager.GetString("LanguageID_082", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English (Serbia).
        /// </summary>
        internal static string LanguageID_083 {
            get {
                return ResourceManager.GetString("LanguageID_083", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Serbian.
        /// </summary>
        internal static string LanguageID_084 {
            get {
                return ResourceManager.GetString("LanguageID_084", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English (Latvia).
        /// </summary>
        internal static string LanguageID_085 {
            get {
                return ResourceManager.GetString("LanguageID_085", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Latvian.
        /// </summary>
        internal static string LanguageID_086 {
            get {
                return ResourceManager.GetString("LanguageID_086", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English (PuertoRico).
        /// </summary>
        internal static string LanguageID_087 {
            get {
                return ResourceManager.GetString("LanguageID_087", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English (Thailand).
        /// </summary>
        internal static string LanguageID_089 {
            get {
                return ResourceManager.GetString("LanguageID_089", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English (Taiwan).
        /// </summary>
        internal static string LanguageID_091 {
            get {
                return ResourceManager.GetString("LanguageID_091", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English (Brazil).
        /// </summary>
        internal static string LanguageID_093 {
            get {
                return ResourceManager.GetString("LanguageID_093", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Portuguese (Brazil).
        /// </summary>
        internal static string LanguageID_094 {
            get {
                return ResourceManager.GetString("LanguageID_094", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Czech Republic.
        /// </summary>
        internal static string LanguageID_203 {
            get {
                return ResourceManager.GetString("LanguageID_203", resourceCulture);
            }
        }
    }
}
