//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "12.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class OrderStatuses {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal OrderStatuses() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.OrderStatuses", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incomplete.
        /// </summary>
        internal static string OrderStatus_00 {
            get {
                return ResourceManager.GetString("OrderStatus_00", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pending.
        /// </summary>
        internal static string OrderStatus_01 {
            get {
                return ResourceManager.GetString("OrderStatus_01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CCDeclined.
        /// </summary>
        internal static string OrderStatus_02 {
            get {
                return ResourceManager.GetString("OrderStatus_02", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ACHDeclined.
        /// </summary>
        internal static string OrderStatus_03 {
            get {
                return ResourceManager.GetString("OrderStatus_03", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancelled.
        /// </summary>
        internal static string OrderStatus_04 {
            get {
                return ResourceManager.GetString("OrderStatus_04", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CCPending.
        /// </summary>
        internal static string OrderStatus_05 {
            get {
                return ResourceManager.GetString("OrderStatus_05", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ACHPending.
        /// </summary>
        internal static string OrderStatus_06 {
            get {
                return ResourceManager.GetString("OrderStatus_06", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accepted.
        /// </summary>
        internal static string OrderStatus_07 {
            get {
                return ResourceManager.GetString("OrderStatus_07", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Printed.
        /// </summary>
        internal static string OrderStatus_08 {
            get {
                return ResourceManager.GetString("OrderStatus_08", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shipped.
        /// </summary>
        internal static string OrderStatus_09 {
            get {
                return ResourceManager.GetString("OrderStatus_09", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PendingInventory.
        /// </summary>
        internal static string OrderStatus_10 {
            get {
                return ResourceManager.GetString("OrderStatus_10", resourceCulture);
            }
        }
    }
}
