//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "12.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class PayableTypes {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal PayableTypes() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.PayableTypes", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mailed Check.
        /// </summary>
        internal static string PayableType_01 {
            get {
                return ResourceManager.GetString("PayableType_01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wire Transfer.
        /// </summary>
        internal static string PayableType_02 {
            get {
                return ResourceManager.GetString("PayableType_02", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payment Card.
        /// </summary>
        internal static string PayableType_05 {
            get {
                return ResourceManager.GetString("PayableType_05", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Direct Deposit.
        /// </summary>
        internal static string PayableType_08 {
            get {
                return ResourceManager.GetString("PayableType_08", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to On Hold.
        /// </summary>
        internal static string PayableType_10 {
            get {
                return ResourceManager.GetString("PayableType_10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bank Wire.
        /// </summary>
        internal static string PayableType_11 {
            get {
                return ResourceManager.GetString("PayableType_11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debit Card Hold.
        /// </summary>
        internal static string PayableType_15 {
            get {
                return ResourceManager.GetString("PayableType_15", resourceCulture);
            }
        }
    }
}
