//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "12.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class PaymentTypes {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal PaymentTypes() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.PaymentTypes", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cash.
        /// </summary>
        internal static string PaymentType_00 {
            get {
                return ResourceManager.GetString("PaymentType_00", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Credit/Debit Card.
        /// </summary>
        internal static string PaymentType_01 {
            get {
                return ResourceManager.GetString("PaymentType_01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check.
        /// </summary>
        internal static string PaymentType_02 {
            get {
                return ResourceManager.GetString("PaymentType_02", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Credit Voucher.
        /// </summary>
        internal static string PaymentType_03 {
            get {
                return ResourceManager.GetString("PaymentType_03", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Net 30.
        /// </summary>
        internal static string PaymentType_04 {
            get {
                return ResourceManager.GetString("PaymentType_04", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Net 60.
        /// </summary>
        internal static string PaymentType_05 {
            get {
                return ResourceManager.GetString("PaymentType_05", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Credit on Account.
        /// </summary>
        internal static string PaymentType_06 {
            get {
                return ResourceManager.GetString("PaymentType_06", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ACH Debit.
        /// </summary>
        internal static string PaymentType_07 {
            get {
                return ResourceManager.GetString("PaymentType_07", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bank Draft.
        /// </summary>
        internal static string PaymentType_08 {
            get {
                return ResourceManager.GetString("PaymentType_08", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wire Transfer.
        /// </summary>
        internal static string PaymentType_09 {
            get {
                return ResourceManager.GetString("PaymentType_09", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Point Redemption.
        /// </summary>
        internal static string PaymentType_10 {
            get {
                return ResourceManager.GetString("PaymentType_10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to COD.
        /// </summary>
        internal static string PaymentType_11 {
            get {
                return ResourceManager.GetString("PaymentType_11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Money Order.
        /// </summary>
        internal static string PaymentType_12 {
            get {
                return ResourceManager.GetString("PaymentType_12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bank Deposit.
        /// </summary>
        internal static string PaymentType_13 {
            get {
                return ResourceManager.GetString("PaymentType_13", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Other 1.
        /// </summary>
        internal static string PaymentType_14 {
            get {
                return ResourceManager.GetString("PaymentType_14", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Other 2.
        /// </summary>
        internal static string PaymentType_15 {
            get {
                return ResourceManager.GetString("PaymentType_15", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Other 3.
        /// </summary>
        internal static string PaymentType_16 {
            get {
                return ResourceManager.GetString("PaymentType_16", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wallet.
        /// </summary>
        internal static string PaymentType_17 {
            get {
                return ResourceManager.GetString("PaymentType_17", resourceCulture);
            }
        }
    }
}
