//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "12.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Ranks {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Ranks() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.Ranks", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unavailable.
        /// </summary>
        internal static string Rank_00 {
            get {
                return ResourceManager.GetString("Rank_00", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Distributor.
        /// </summary>
        internal static string Rank_01 {
            get {
                return ResourceManager.GetString("Rank_01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to C-200.
        /// </summary>
        internal static string Rank_02 {
            get {
                return ResourceManager.GetString("Rank_02", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to C-500.
        /// </summary>
        internal static string Rank_03 {
            get {
                return ResourceManager.GetString("Rank_03", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bronze.
        /// </summary>
        internal static string Rank_04 {
            get {
                return ResourceManager.GetString("Rank_04", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Silver.
        /// </summary>
        internal static string Rank_05 {
            get {
                return ResourceManager.GetString("Rank_05", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gold.
        /// </summary>
        internal static string Rank_06 {
            get {
                return ResourceManager.GetString("Rank_06", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Executive.
        /// </summary>
        internal static string Rank_07 {
            get {
                return ResourceManager.GetString("Rank_07", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ruby Executive.
        /// </summary>
        internal static string Rank_08 {
            get {
                return ResourceManager.GetString("Rank_08", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Emerald Executive.
        /// </summary>
        internal static string Rank_09 {
            get {
                return ResourceManager.GetString("Rank_09", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Diamond Executive.
        /// </summary>
        internal static string Rank_10 {
            get {
                return ResourceManager.GetString("Rank_10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Double Diamond Executive.
        /// </summary>
        internal static string Rank_11 {
            get {
                return ResourceManager.GetString("Rank_11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Platinum Executive.
        /// </summary>
        internal static string Rank_12 {
            get {
                return ResourceManager.GetString("Rank_12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Double Platinum Executive.
        /// </summary>
        internal static string Rank_13 {
            get {
                return ResourceManager.GetString("Rank_13", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Triple Platinum Executive.
        /// </summary>
        internal static string Rank_14 {
            get {
                return ResourceManager.GetString("Rank_14", resourceCulture);
            }
        }
    }
}
