//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources
{


    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "12.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Common {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Common() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.Common", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Retail Sales Commissions.
        /// </summary>
        internal static string Bonus_1_001 {
            get {
                return ResourceManager.GetString("Bonus_1_001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Party Commissions.
        /// </summary>
        internal static string Bonus_1_111 {
            get {
                return ResourceManager.GetString("Bonus_1_111", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enhanced Personal Commission.
        /// </summary>
        internal static string Bonus_2_021 {
            get {
                return ResourceManager.GetString("Bonus_2_021", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enhanced Personal Commission Training Bonus.
        /// </summary>
        internal static string Bonus_2_022 {
            get {
                return ResourceManager.GetString("Bonus_2_022", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Management Level Bonus.
        /// </summary>
        internal static string Bonus_2_023 {
            get {
                return ResourceManager.GetString("Bonus_2_023", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enroller Bonus.
        /// </summary>
        internal static string Bonus_2_024 {
            get {
                return ResourceManager.GetString("Bonus_2_024", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Leader Generation Bonus.
        /// </summary>
        internal static string Bonus_2_025 {
            get {
                return ResourceManager.GetString("Bonus_2_025", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generation Bonus.
        /// </summary>
        internal static string Bonus_2_026 {
            get {
                return ResourceManager.GetString("Bonus_2_026", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please re-enter your password.
        /// </summary>
        internal static string ConfirmPassword {
            get {
                return ResourceManager.GetString("ConfirmPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown.
        /// </summary>
        internal static string CreditCardType_01 {
            get {
                return ResourceManager.GetString("CreditCardType_01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Visa.
        /// </summary>
        internal static string CreditCardType_02 {
            get {
                return ResourceManager.GetString("CreditCardType_02", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MasterCard.
        /// </summary>
        internal static string CreditCardType_03 {
            get {
                return ResourceManager.GetString("CreditCardType_03", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amex.
        /// </summary>
        internal static string CreditCardType_04 {
            get {
                return ResourceManager.GetString("CreditCardType_04", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Discover.
        /// </summary>
        internal static string CreditCardType_05 {
            get {
                return ResourceManager.GetString("CreditCardType_05", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Switch.
        /// </summary>
        internal static string CreditCardType_06 {
            get {
                return ResourceManager.GetString("CreditCardType_06", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Solo.
        /// </summary>
        internal static string CreditCardType_07 {
            get {
                return ResourceManager.GetString("CreditCardType_07", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to JCB.
        /// </summary>
        internal static string CreditCardType_08 {
            get {
                return ResourceManager.GetString("CreditCardType_08", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maestro.
        /// </summary>
        internal static string CreditCardType_09 {
            get {
                return ResourceManager.GetString("CreditCardType_09", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delta.
        /// </summary>
        internal static string CreditCardType_10 {
            get {
                return ResourceManager.GetString("CreditCardType_10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Laser.
        /// </summary>
        internal static string CreditCardType_11 {
            get {
                return ResourceManager.GetString("CreditCardType_11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ECMC.
        /// </summary>
        internal static string CreditCardType_12 {
            get {
                return ResourceManager.GetString("CreditCardType_12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BHS.
        /// </summary>
        internal static string CreditCardType_13 {
            get {
                return ResourceManager.GetString("CreditCardType_13", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IKEA.
        /// </summary>
        internal static string CreditCardType_14 {
            get {
                return ResourceManager.GetString("CreditCardType_14", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Diners.
        /// </summary>
        internal static string CreditCardType_15 {
            get {
                return ResourceManager.GetString("CreditCardType_15", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CB.
        /// </summary>
        internal static string CreditCardType_16 {
            get {
                return ResourceManager.GetString("CreditCardType_16", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Carte Bleue.
        /// </summary>
        internal static string CreditCardType_17 {
            get {
                return ResourceManager.GetString("CreditCardType_17", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dankort.
        /// </summary>
        internal static string CreditCardType_18 {
            get {
                return ResourceManager.GetString("CreditCardType_18", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aurore.
        /// </summary>
        internal static string CreditCardType_19 {
            get {
                return ResourceManager.GetString("CreditCardType_19", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GE Capital.
        /// </summary>
        internal static string CreditCardType_20 {
            get {
                return ResourceManager.GetString("CreditCardType_20", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AirPlus.
        /// </summary>
        internal static string CreditCardType_21 {
            get {
                return ResourceManager.GetString("CreditCardType_21", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UATP.
        /// </summary>
        internal static string CreditCardType_22 {
            get {
                return ResourceManager.GetString("CreditCardType_22", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Carte Blanche.
        /// </summary>
        internal static string CreditCardType_23 {
            get {
                return ResourceManager.GetString("CreditCardType_23", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Visa Electron.
        /// </summary>
        internal static string CreditCardType_24 {
            get {
                return ResourceManager.GetString("CreditCardType_24", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to JAL.
        /// </summary>
        internal static string CreditCardType_25 {
            get {
                return ResourceManager.GetString("CreditCardType_25", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GE Money.
        /// </summary>
        internal static string CreditCardType_26 {
            get {
                return ResourceManager.GetString("CreditCardType_26", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to En Route.
        /// </summary>
        internal static string CreditCardType_27 {
            get {
                return ResourceManager.GetString("CreditCardType_27", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Carta Si.
        /// </summary>
        internal static string CreditCardType_28 {
            get {
                return ResourceManager.GetString("CreditCardType_28", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Galeria.
        /// </summary>
        internal static string CreditCardType_29 {
            get {
                return ResourceManager.GetString("CreditCardType_29", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CRM Falabella.
        /// </summary>
        internal static string CreditCardType_30 {
            get {
                return ResourceManager.GetString("CreditCardType_30", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debito Maestro.
        /// </summary>
        internal static string CreditCardType_31 {
            get {
                return ResourceManager.GetString("CreditCardType_31", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to V PAY.
        /// </summary>
        internal static string CreditCardType_32 {
            get {
                return ResourceManager.GetString("CreditCardType_32", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to China UnionPay.
        /// </summary>
        internal static string CreditCardType_33 {
            get {
                return ResourceManager.GetString("CreditCardType_33", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deleted.
        /// </summary>
        internal static string CustomerStatus_00 {
            get {
                return ResourceManager.GetString("CustomerStatus_00", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Active.
        /// </summary>
        internal static string CustomerStatus_01 {
            get {
                return ResourceManager.GetString("CustomerStatus_01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inactive.
        /// </summary>
        internal static string CustomerStatus_02 {
            get {
                return ResourceManager.GetString("CustomerStatus_02", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Suspended.
        /// </summary>
        internal static string CustomerStatus_03 {
            get {
                return ResourceManager.GetString("CustomerStatus_03", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Terminated.
        /// </summary>
        internal static string CustomerStatus_04 {
            get {
                return ResourceManager.GetString("CustomerStatus_04", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pending Termination.
        /// </summary>
        internal static string CustomerStatus_05 {
            get {
                return ResourceManager.GetString("CustomerStatus_05", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancelled.
        /// </summary>
        internal static string CustomerStatus_06 {
            get {
                return ResourceManager.GetString("CustomerStatus_06", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Employee.
        /// </summary>
        internal static string CustomerType_01 {
            get {
                return ResourceManager.GetString("CustomerType_01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Retail Customer.
        /// </summary>
        internal static string CustomerType_02 {
            get {
                return ResourceManager.GetString("CustomerType_02", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Independent Ambassador.
        /// </summary>
        internal static string CustomerType_03 {
            get {
                return ResourceManager.GetString("CustomerType_03", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Host.
        /// </summary>
        internal static string CustomerType_04 {
            get {
                return ResourceManager.GetString("CustomerType_04", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Host Prospect.
        /// </summary>
        internal static string CustomerType_05 {
            get {
                return ResourceManager.GetString("CustomerType_05", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lead.
        /// </summary>
        internal static string CustomerType_06 {
            get {
                return ResourceManager.GetString("CustomerType_06", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Party Guest.
        /// </summary>
        internal static string CustomerType_07 {
            get {
                return ResourceManager.GetString("CustomerType_07", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Party.
        /// </summary>
        internal static string CustomerType_08 {
            get {
                return ResourceManager.GetString("CustomerType_08", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forgot Your Password?.
        /// </summary>
        internal static string ForgotPassword {
            get {
                return ResourceManager.GetString("ForgotPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter your login ID (usually email) and we&apos;ll email you instructions to reset your password..
        /// </summary>
        internal static string ForgotPasswordInstructions {
            get {
                return ResourceManager.GetString("ForgotPasswordInstructions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weekly.
        /// </summary>
        internal static string FrequencyType_01 {
            get {
                return ResourceManager.GetString("FrequencyType_01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Every Two Weeks.
        /// </summary>
        internal static string FrequencyType_02 {
            get {
                return ResourceManager.GetString("FrequencyType_02", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Monthly.
        /// </summary>
        internal static string FrequencyType_03 {
            get {
                return ResourceManager.GetString("FrequencyType_03", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quarterly.
        /// </summary>
        internal static string FrequencyType_04 {
            get {
                return ResourceManager.GetString("FrequencyType_04", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Twice a Year.
        /// </summary>
        internal static string FrequencyType_05 {
            get {
                return ResourceManager.GetString("FrequencyType_05", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yearly.
        /// </summary>
        internal static string FrequencyType_06 {
            get {
                return ResourceManager.GetString("FrequencyType_06", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bi-Monthly.
        /// </summary>
        internal static string FrequencyType_07 {
            get {
                return ResourceManager.GetString("FrequencyType_07", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Every 4 weeks.
        /// </summary>
        internal static string FrequencyType_08 {
            get {
                return ResourceManager.GetString("FrequencyType_08", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Every 6 Weeks.
        /// </summary>
        internal static string FrequencyType_09 {
            get {
                return ResourceManager.GetString("FrequencyType_09", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Every 8 Weeks.
        /// </summary>
        internal static string FrequencyType_10 {
            get {
                return ResourceManager.GetString("FrequencyType_10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Every 12 Weeks.
        /// </summary>
        internal static string FrequencyType_11 {
            get {
                return ResourceManager.GetString("FrequencyType_11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English.
        /// </summary>
        internal static string Language_000 {
            get {
                return ResourceManager.GetString("Language_000", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incomplete.
        /// </summary>
        internal static string OrderStatus_00 {
            get {
                return ResourceManager.GetString("OrderStatus_00", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pending.
        /// </summary>
        internal static string OrderStatus_01 {
            get {
                return ResourceManager.GetString("OrderStatus_01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CC Declined.
        /// </summary>
        internal static string OrderStatus_02 {
            get {
                return ResourceManager.GetString("OrderStatus_02", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ACH Declined.
        /// </summary>
        internal static string OrderStatus_03 {
            get {
                return ResourceManager.GetString("OrderStatus_03", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancelled.
        /// </summary>
        internal static string OrderStatus_04 {
            get {
                return ResourceManager.GetString("OrderStatus_04", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CC Pending.
        /// </summary>
        internal static string OrderStatus_05 {
            get {
                return ResourceManager.GetString("OrderStatus_05", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ACH Pending.
        /// </summary>
        internal static string OrderStatus_06 {
            get {
                return ResourceManager.GetString("OrderStatus_06", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accepted.
        /// </summary>
        internal static string OrderStatus_07 {
            get {
                return ResourceManager.GetString("OrderStatus_07", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Printed.
        /// </summary>
        internal static string OrderStatus_08 {
            get {
                return ResourceManager.GetString("OrderStatus_08", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shipped.
        /// </summary>
        internal static string OrderStatus_09 {
            get {
                return ResourceManager.GetString("OrderStatus_09", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pending Inventory.
        /// </summary>
        internal static string OrderStatus_10 {
            get {
                return ResourceManager.GetString("OrderStatus_10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        internal static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cash.
        /// </summary>
        internal static string PayableType_00 {
            get {
                return ResourceManager.GetString("PayableType_00", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Credit Card.
        /// </summary>
        internal static string PayableType_01 {
            get {
                return ResourceManager.GetString("PayableType_01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check.
        /// </summary>
        internal static string PayableType_02 {
            get {
                return ResourceManager.GetString("PayableType_02", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Credit Voucher.
        /// </summary>
        internal static string PayableType_03 {
            get {
                return ResourceManager.GetString("PayableType_03", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Net 30.
        /// </summary>
        internal static string PayableType_04 {
            get {
                return ResourceManager.GetString("PayableType_04", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Net 60.
        /// </summary>
        internal static string PayableType_05 {
            get {
                return ResourceManager.GetString("PayableType_05", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use Credit.
        /// </summary>
        internal static string PayableType_06 {
            get {
                return ResourceManager.GetString("PayableType_06", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ACH Debit.
        /// </summary>
        internal static string PayableType_07 {
            get {
                return ResourceManager.GetString("PayableType_07", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bank Draft.
        /// </summary>
        internal static string PayableType_08 {
            get {
                return ResourceManager.GetString("PayableType_08", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wire Transfer.
        /// </summary>
        internal static string PayableType_09 {
            get {
                return ResourceManager.GetString("PayableType_09", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Point Redemption.
        /// </summary>
        internal static string PayableType_10 {
            get {
                return ResourceManager.GetString("PayableType_10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to COD.
        /// </summary>
        internal static string PayableType_11 {
            get {
                return ResourceManager.GetString("PayableType_11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Money Order.
        /// </summary>
        internal static string PayableType_12 {
            get {
                return ResourceManager.GetString("PayableType_12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bank Deposit.
        /// </summary>
        internal static string PayableType_13 {
            get {
                return ResourceManager.GetString("PayableType_13", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Other 1.
        /// </summary>
        internal static string PayableType_14 {
            get {
                return ResourceManager.GetString("PayableType_14", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Other 2.
        /// </summary>
        internal static string PayableType_15 {
            get {
                return ResourceManager.GetString("PayableType_15", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Other 3.
        /// </summary>
        internal static string PayableType_16 {
            get {
                return ResourceManager.GetString("PayableType_16", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wallet.
        /// </summary>
        internal static string PayableType_17 {
            get {
                return ResourceManager.GetString("PayableType_17", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cash.
        /// </summary>
        internal static string PaymentType_00 {
            get {
                return ResourceManager.GetString("PaymentType_00", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Credit Card.
        /// </summary>
        internal static string PaymentType_01 {
            get {
                return ResourceManager.GetString("PaymentType_01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check.
        /// </summary>
        internal static string PaymentType_02 {
            get {
                return ResourceManager.GetString("PaymentType_02", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Credit Voucher.
        /// </summary>
        internal static string PaymentType_03 {
            get {
                return ResourceManager.GetString("PaymentType_03", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Net 30.
        /// </summary>
        internal static string PaymentType_04 {
            get {
                return ResourceManager.GetString("PaymentType_04", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Net 60.
        /// </summary>
        internal static string PaymentType_05 {
            get {
                return ResourceManager.GetString("PaymentType_05", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use Credit.
        /// </summary>
        internal static string PaymentType_06 {
            get {
                return ResourceManager.GetString("PaymentType_06", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ACH Debit.
        /// </summary>
        internal static string PaymentType_07 {
            get {
                return ResourceManager.GetString("PaymentType_07", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bank Draft.
        /// </summary>
        internal static string PaymentType_08 {
            get {
                return ResourceManager.GetString("PaymentType_08", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wire Transfer.
        /// </summary>
        internal static string PaymentType_09 {
            get {
                return ResourceManager.GetString("PaymentType_09", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Point Redemption.
        /// </summary>
        internal static string PaymentType_10 {
            get {
                return ResourceManager.GetString("PaymentType_10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to COD.
        /// </summary>
        internal static string PaymentType_11 {
            get {
                return ResourceManager.GetString("PaymentType_11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Money Order.
        /// </summary>
        internal static string PaymentType_12 {
            get {
                return ResourceManager.GetString("PaymentType_12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bank Deposit.
        /// </summary>
        internal static string PaymentType_13 {
            get {
                return ResourceManager.GetString("PaymentType_13", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Other 1.
        /// </summary>
        internal static string PaymentType_14 {
            get {
                return ResourceManager.GetString("PaymentType_14", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Other 2.
        /// </summary>
        internal static string PaymentType_15 {
            get {
                return ResourceManager.GetString("PaymentType_15", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Other 3.
        /// </summary>
        internal static string PaymentType_16 {
            get {
                return ResourceManager.GetString("PaymentType_16", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wallet.
        /// </summary>
        internal static string PaymentType_17 {
            get {
                return ResourceManager.GetString("PaymentType_17", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weekly.
        /// </summary>
        internal static string PeriodType_001 {
            get {
                return ResourceManager.GetString("PeriodType_001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Monthly.
        /// </summary>
        internal static string PeriodType_002 {
            get {
                return ResourceManager.GetString("PeriodType_002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Host Rewards Cash.
        /// </summary>
        internal static string PointAccount_01 {
            get {
                return ResourceManager.GetString("PointAccount_01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Host 1/2 off credits.
        /// </summary>
        internal static string PointAccount_02 {
            get {
                return ResourceManager.GetString("PointAccount_02", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bookings Rewards Cash.
        /// </summary>
        internal static string PointAccount_03 {
            get {
                return ResourceManager.GetString("PointAccount_03", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Party Sales Total.
        /// </summary>
        internal static string PointAccount_04 {
            get {
                return ResourceManager.GetString("PointAccount_04", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Booking Rewards Earned.
        /// </summary>
        internal static string PointAccount_05 {
            get {
                return ResourceManager.GetString("PointAccount_05", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Rank_00 {
            get {
                return ResourceManager.GetString("Rank_00", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ambassador.
        /// </summary>
        internal static string Rank_01 {
            get {
                return ResourceManager.GetString("Rank_01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ambassador.
        /// </summary>
        internal static string Rank_10 {
            get {
                return ResourceManager.GetString("Rank_10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Senior Ambassador.
        /// </summary>
        internal static string Rank_15 {
            get {
                return ResourceManager.GetString("Rank_15", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Associate Director.
        /// </summary>
        internal static string Rank_20 {
            get {
                return ResourceManager.GetString("Rank_20", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Director.
        /// </summary>
        internal static string Rank_30 {
            get {
                return ResourceManager.GetString("Rank_30", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Senior Director.
        /// </summary>
        internal static string Rank_40 {
            get {
                return ResourceManager.GetString("Rank_40", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Executive Director.
        /// </summary>
        internal static string Rank_50 {
            get {
                return ResourceManager.GetString("Rank_50", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to National Director.
        /// </summary>
        internal static string Rank_60 {
            get {
                return ResourceManager.GetString("Rank_60", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send.
        /// </summary>
        internal static string Send {
            get {
                return ResourceManager.GetString("Send", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign in.
        /// </summary>
        internal static string SignIn {
            get {
                return ResourceManager.GetString("SignIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Web Platform (Backoffice) Subscription.
        /// </summary>
        internal static string Subscription_01 {
            get {
                return ResourceManager.GetString("Subscription_01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username.
        /// </summary>
        internal static string Username {
            get {
                return ResourceManager.GetString("Username", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Supplies.
        /// </summary>
        internal static string WebCategory_15 {
            get {
                return ResourceManager.GetString("WebCategory_15", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Beauty.
        /// </summary>
        internal static string WebCategory_16 {
            get {
                return ResourceManager.GetString("WebCategory_16", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Handbags.
        /// </summary>
        internal static string WebCategory_17 {
            get {
                return ResourceManager.GetString("WebCategory_17", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jewelry.
        /// </summary>
        internal static string WebCategory_73 {
            get {
                return ResourceManager.GetString("WebCategory_73", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accessories.
        /// </summary>
        internal static string WebCategory_74 {
            get {
                return ResourceManager.GetString("WebCategory_74", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spring 17.
        /// </summary>
        internal static string WebCategory_95 {
            get {
                return ResourceManager.GetString("WebCategory_95", resourceCulture);
            }
        }
    }
}
