#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Common.Views.Shared.EditorTemplates
{
    using Common;
    using Common.Helpers;
    using Common.HtmlHelpers;
    using Common.Services;
    using ExigoService;
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Linq.Expressions;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Optimization;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Shared/EditorTemplates/Address.cshtml")]
    public partial class _Address : System.Web.Mvc.WebViewPage<Address>
    {
        public _Address()
        {
        }
        public override void Execute()
        {
            
            #line 2 "..\..\Views\Shared\EditorTemplates\Address.cshtml"
  
    var contextID = Guid.NewGuid().ToString();

    var defaultCountryCode = (Model.Country.IsNotNullOrEmpty()) ? Model.Country : GlobalSettings.Company.Address.Country;
    var defaultRegionCode = (Model.State.IsNotNullOrEmpty()) ? Model.State : GlobalSettings.Company.Address.State;
    var isVerifyable = ViewData["VerifyEnabled"] == null || Convert.ToBoolean(ViewData["VerifyEnabled"]) == true;

            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n<div");

WriteLiteral(" class=\"view-address\"");

WriteAttribute("id", Tuple.Create(" id=\"", 454), Tuple.Create("\"", 482)
, Tuple.Create(Tuple.Create("", 459), Tuple.Create("view-address-", 459), true)
            
            #line 10 "..\..\Views\Shared\EditorTemplates\Address.cshtml"
, Tuple.Create(Tuple.Create("", 472), Tuple.Create<System.Object, System.Int32>(contextID
            
            #line default
            #line hidden
, 472), false)
);

WriteLiteral(">\r\n\r\n");

WriteLiteral("    ");

            
            #line 12 "..\..\Views\Shared\EditorTemplates\Address.cshtml"
Write(Html.HiddenFor(c => c.AddressType, new { data_role = "AddressType" }));

            
            #line default
            #line hidden
WriteLiteral(" \r\n\r\n    <div");

WriteLiteral(" class=\"form-group\"");

WriteLiteral(">\r\n");

WriteLiteral("        ");

            
            #line 15 "..\..\Views\Shared\EditorTemplates\Address.cshtml"
   Write(Html.LabelFor(c => c.Country, new { @class = "control-label" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("        ");

            
            #line 16 "..\..\Views\Shared\EditorTemplates\Address.cshtml"
   Write(Html.DropDownListFor(c => c.Country,
            selectList: Html.Countries(defaultCountryCode),
            htmlAttributes: new 
            {
                @class = "form-control NewCard-Country",
                data_region_bind = "#" + Html.IdFor(c => c.State) + "_" + contextID,
                data_address_bind = "#" + Html.IdFor(c => c.Address2) + "_" + contextID,
                data_role = "Country"
            }));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("        ");

            
            #line 25 "..\..\Views\Shared\EditorTemplates\Address.cshtml"
   Write(Html.ValidationMessageFor(c => c.Country));

            
            #line default
            #line hidden
WriteLiteral("\r\n    </div>\r\n\r\n    <div");

WriteLiteral(" class=\"form-group address \"");

WriteLiteral(">\r\n\r\n");

WriteLiteral("        ");

            
            #line 29 "..\..\Views\Shared\EditorTemplates\Address.cshtml"
   Write(Html.LabelFor(c => c.Address1, new { @class = "control-label" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n");
WriteLiteral("        ");

            
            #line 30 "..\..\Views\Shared\EditorTemplates\Address.cshtml"
    Write(Html.EditorFor(c => c.Address1, new { data_role = "Address1"}));

            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n        <div");

WriteLiteral(" class=\"space-5 address1\"");

WriteLiteral("></div>\r\n        <div");

WriteLiteral(" class=\"form-group\"");

WriteLiteral(" ");

            
            #line 33 "..\..\Views\Shared\EditorTemplates\Address.cshtml"
                                 if (defaultCountryCode == "US") {
            
            #line default
            #line hidden
WriteLiteral(" ");

WriteLiteral(" style=\"display: none;\" ");

WriteLiteral("      ");

            
            #line 33 "..\..\Views\Shared\EditorTemplates\Address.cshtml"
                                                                                                              }
            
            #line default
            #line hidden
WriteLiteral(">\r\n");

WriteLiteral("            ");

            
            #line 34 "..\..\Views\Shared\EditorTemplates\Address.cshtml"
       Write(Html.EditorFor(c => c.Address2, new
            {
                id = Html.IdFor(c => c.Address2) + "_" + contextID,
                data_role = "Address2"
            }));

            
            #line default
            #line hidden
WriteLiteral("\r\n        </div>\r\n    </div>\r\n\r\n\r\n    <label");

WriteAttribute("for", Tuple.Create(" for=\"", 1731), Tuple.Create("\"", 1763)
            
            #line 43 "..\..\Views\Shared\EditorTemplates\Address.cshtml"
, Tuple.Create(Tuple.Create("", 1737), Tuple.Create<System.Object, System.Int32>(Html.NameFor(c => c.City)
            
            #line default
            #line hidden
, 1737), false)
);

WriteLiteral(" class=\"control-label hidden-xs\"");

WriteLiteral(">City / State / Zip</label>\r\n    <div");

WriteLiteral(" class=\"row margin-5\"");

WriteLiteral(">\r\n        <div");

WriteLiteral(" class=\"col-xs-4\"");

WriteLiteral(">\r\n            <div");

WriteLiteral(" class=\"form-group\"");

WriteLiteral(">\r\n");

WriteLiteral("                ");

            
            #line 47 "..\..\Views\Shared\EditorTemplates\Address.cshtml"
           Write(Html.LabelFor(c => c.City, new { @class = "control-label visible-xs" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("                ");

            
            #line 48 "..\..\Views\Shared\EditorTemplates\Address.cshtml"
           Write(Html.EditorFor(c => c.City, new { data_role = "City" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n            </div>\r\n        </div>\r\n        <div");

WriteLiteral(" class=\"col-xs-5\"");

WriteLiteral(">\r\n            <div");

WriteLiteral(" class=\"form-group \"");

WriteLiteral(">\r\n");

WriteLiteral("                ");

           

            #line 53 "..\..\Views\Shared\EditorTemplates\Address.cshtml"
           Write(Html.LabelFor(c => c.State, new { @class = "control-label visible-xs" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("                ");

            
            #line 54 "..\..\Views\Shared\EditorTemplates\Address.cshtml"
           Write(Html.DropDownListFor(c => c.State,
                    selectList: Html.Regions(defaultCountryCode, defaultRegionCode),
                    htmlAttributes: new
                    {
                        @class = "form-control ",
                        id = Html.IdFor(c => c.State) + "_" + contextID,
                        data_role = "State"
                    }));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("                ");

            
            #line 62 "..\..\Views\Shared\EditorTemplates\Address.cshtml"
           Write(Html.ValidationMessageFor(c => c.State));

            
            #line default
            #line hidden
WriteLiteral("\r\n            </div>\r\n        </div>\r\n\r\n        <div");

WriteLiteral(" class=\"col-xs-3\"");

WriteLiteral(">\r\n            <div");

WriteLiteral(" class=\"form-group\"");

WriteLiteral(">\r\n");

WriteLiteral("                ");

            
            #line 68 "..\..\Views\Shared\EditorTemplates\Address.cshtml"
           Write(Html.LabelFor(c => c.Zip, new { @class = "control-label visible-xs" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("                ");

            
            #line 69 "..\..\Views\Shared\EditorTemplates\Address.cshtml"
           Write(Html.EditorFor(c => c.Zip, new { data_role = "Zip", data_restrict_input = "zipcode" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n            </div>\r\n        </div>\r\n    </div>\r\n\r\n");

            
            #line 74 "..\..\Views\Shared\EditorTemplates\Address.cshtml"
    
            
            #line default
            #line hidden
            
            #line 74 "..\..\Views\Shared\EditorTemplates\Address.cshtml"
     if (isVerifyable)
    {

            
            #line default
            #line hidden
WriteLiteral("        <div");

WriteLiteral(" class=\"row margin-5\"");
WriteLiteral(">\r\n ");
//WriteLiteral(">\r\n            <div");

//WriteLiteral(" class=\"col-xs-12\"");

//WriteLiteral(">\r\n                <button");

//WriteLiteral(" type=\"button\"");

//WriteLiteral(" class=\"btn btn-info\"");

//WriteLiteral(" data-role=\"verify\"");

//WriteLiteral(">Verify Address</button>\r\n            </div>\r\n        </div>\r\n");

            
            #line 81 "..\..\Views\Shared\EditorTemplates\Address.cshtml"
    }

            
            #line default
            #line hidden
WriteLiteral("</div>\r\n\r\n\r\n\r\n");

            
            #line 86 "..\..\Views\Shared\EditorTemplates\Address.cshtml"
 using (Html.BeginPartialScript())
{

            
            #line default
            #line hidden
WriteLiteral("    <script>\r\n        require([\"modules/addresses\"], function (address) {\r\n      " +
"      address.bind(\'#view-address-");

            
            #line 90 "..\..\Views\Shared\EditorTemplates\Address.cshtml"
                                   Write(contextID);

            
            #line default
            #line hidden
WriteLiteral("\');\r\n        });\r\n    </script>\r\n");

            
            #line 93 "..\..\Views\Shared\EditorTemplates\Address.cshtml"
}
            
            #line default
            #line hidden
        }
    }
}
#pragma warning restore 1591
