#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Common.Views.Shared.EditorTemplates
{
    using Common;
    using Common.Helpers;
    using Common.HtmlHelpers;
    using Common.Services;
    using ExigoService;
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Linq.Expressions;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Optimization;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Shared/EditorTemplates/BankAccount.cshtml")]
    public partial class _BankAccount : System.Web.Mvc.WebViewPage<BankAccount>
    {
        public _BankAccount()
        {
        }
        public override void Execute()
        {
            
            #line 2 "..\..\Views\Shared\EditorTemplates\BankAccount.cshtml"
  
    var contextID = Guid.NewGuid().ToString();

    Model.BillingAddress = Model.BillingAddress ?? new Address();
    var defaultCountryCode = (Model.BillingAddress.Country.IsNotNullOrEmpty()) ? Model.BillingAddress.Country : GlobalSettings.Company.Address.Country;
    var defaultRegionCode = (Model.BillingAddress.State.IsNotNullOrEmpty()) ? Model.BillingAddress.State : GlobalSettings.Company.Address.State;

            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n<div");

WriteLiteral(" class=\"view-bankaccount\"");

WriteAttribute("id", Tuple.Create(" id=\"", 474), Tuple.Create("\"", 506)
, Tuple.Create(Tuple.Create("", 479), Tuple.Create("view-bankaccount-", 479), true)
            
            #line 10 "..\..\Views\Shared\EditorTemplates\BankAccount.cshtml"
, Tuple.Create(Tuple.Create("", 496), Tuple.Create<System.Object, System.Int32>(contextID
            
            #line default
            #line hidden
, 496), false)
);

WriteLiteral(">\r\n\r\n    <input");

WriteLiteral(" type=\"hidden\"");

WriteAttribute("name", Tuple.Create(" name=\"", 536), Tuple.Create("\"", 618)
            
            #line 12 "..\..\Views\Shared\EditorTemplates\BankAccount.cshtml"
, Tuple.Create(Tuple.Create("", 543), Tuple.Create<System.Object, System.Int32>(Html.ViewContext.ViewData.TemplateInfo.HtmlFieldPrefix
            
            #line default
            #line hidden
, 543), false)
, Tuple.Create(Tuple.Create("", 600), Tuple.Create(".PaymentMethodType", 600), true)
);

WriteAttribute("value", Tuple.Create(" value=\"", 619), Tuple.Create("\"", 654)
            
            #line 12 "..\..\Views\Shared\EditorTemplates\BankAccount.cshtml"
                                    , Tuple.Create(Tuple.Create("", 627), Tuple.Create<System.Object, System.Int32>(Model.GetType().ToString()
            
            #line default
            #line hidden
, 627), false)
);

WriteLiteral(" />\r\n");

WriteLiteral("    ");

            
            #line 13 "..\..\Views\Shared\EditorTemplates\BankAccount.cshtml"
Write(Html.HiddenFor(c => c.Type));

            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n\r\n    <div");

WriteLiteral(" class=\"row margin-5\"");

WriteLiteral(">\r\n        <div");

WriteLiteral(" class=\"col-sm-6\"");

WriteLiteral(">\r\n            <div");

WriteLiteral(" class=\"form-group\"");

WriteLiteral(">\r\n");

WriteLiteral("                ");

            
            #line 19 "..\..\Views\Shared\EditorTemplates\BankAccount.cshtml"
           Write(Html.EditorFor(c => c.NameOnAccount));

            
            #line default
            #line hidden
WriteLiteral("\r\n            </div>\r\n        </div>\r\n        <div");

WriteLiteral(" class=\"col-sm-6\"");

WriteLiteral(">\r\n            <div");

WriteLiteral(" class=\"form-group\"");

WriteLiteral(">\r\n");

WriteLiteral("                ");

            
            #line 24 "..\..\Views\Shared\EditorTemplates\BankAccount.cshtml"
           Write(Html.EditorFor(c => c.BankName));

            
            #line default
            #line hidden
WriteLiteral("\r\n            </div>\r\n        </div>\r\n    </div>\r\n\r\n    <div");

WriteLiteral(" class=\"row margin-5\"");

WriteLiteral(">\r\n        <div");

WriteLiteral(" class=\"col-sm-6\"");

WriteLiteral(">\r\n            <div");

WriteLiteral(" class=\"form-group\"");

WriteLiteral(">\r\n");

WriteLiteral("                ");

            
            #line 32 "..\..\Views\Shared\EditorTemplates\BankAccount.cshtml"
           Write(Html.EditorFor(c => c.AccountNumber));

            
            #line default
            #line hidden
WriteLiteral("\r\n            </div>\r\n        </div>\r\n        <div");

WriteLiteral(" class=\"col-sm-6\"");

WriteLiteral(">\r\n            <div");

WriteLiteral(" class=\"form-group\"");

WriteLiteral(">\r\n");

WriteLiteral("                ");

            
            #line 37 "..\..\Views\Shared\EditorTemplates\BankAccount.cshtml"
           Write(Html.EditorFor(c => c.RoutingNumber, new { data_restrict_input = "int" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n            </div>\r\n        </div>\r\n    </div>\r\n\r\n    <hr />\r\n\r\n");

WriteLiteral("    ");

            
            #line 44 "..\..\Views\Shared\EditorTemplates\BankAccount.cshtml"
Write(Html.EditorFor(c => Model.BillingAddress, "Address", new { VerifyEnabled = false }));

            
            #line default
            #line hidden
WriteLiteral("\r\n</div>\r\n");

        }
    }
}
#pragma warning restore 1591
