#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Common.Views.Shared.EditorTemplates
{
    using Common;
    using Common.Helpers;
    using Common.HtmlHelpers;
    using Common.Services;
    using ExigoService;
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Linq.Expressions;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Optimization;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Shared/EditorTemplates/BirthDate.cshtml")]
    public partial class _BirthDate : System.Web.Mvc.WebViewPage<DateTime>
    {
        public _BirthDate()
        {
        }
        public override void Execute()
        {
            
            #line 2 "..\..\Views\Shared\EditorTemplates\BirthDate.cshtml"
  
    Layout = "~/Views/Shared/EditorTemplates/_FormField.cshtml";

    var htmlAttributes = Html.GetEditorHtmlAttributes(new
    {
        @class = "form-control"
    });

            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n<div");

WriteLiteral(" class=\"row\"");

WriteLiteral(">\r\n    <div");

WriteLiteral(" class=\"col-sm-6\"");

WriteLiteral(">\r\n");

WriteLiteral("        ");

            
            #line 13 "..\..\Views\Shared\EditorTemplates\BirthDate.cshtml"
   Write(Html.DropDownList("Month", Html.Months().Select(item => {
           item.Selected = Convert.ToInt32(item.Value) == Model.Month;
           return item;
        }), htmlAttributes));

            
            #line default
            #line hidden
WriteLiteral("\r\n    </div>\r\n    <div");

WriteLiteral(" class=\"col-sm-2\"");

WriteLiteral(">\r\n");

WriteLiteral("        ");

            
            #line 19 "..\..\Views\Shared\EditorTemplates\BirthDate.cshtml"
   Write(Html.DropDownList("Day", Html.Days().Select(item => {
           item.Selected = Convert.ToInt32(item.Value) == Model.Day;
           return item;
        }), htmlAttributes));

            
            #line default
            #line hidden
WriteLiteral("\r\n    </div>\r\n    <div");

WriteLiteral(" class=\"col-sm-4\"");

WriteLiteral(">\r\n");

WriteLiteral("        ");

            
            #line 25 "..\..\Views\Shared\EditorTemplates\BirthDate.cshtml"
   Write(Html.DropDownList("Year", Html.Years(DateTime.Now.AddYears(-18).Year, 80).Select(item => {
           item.Selected = Convert.ToInt32(item.Value) == Model.Year;
           return item;
       }), htmlAttributes));

            
            #line default
            #line hidden
WriteLiteral("\r\n    </div>\r\n</div>");

        }
    }
}
#pragma warning restore 1591
