#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Common.Views.Shared.EditorTemplates
{
    using Common;
    using Common.Helpers;
    using Common.HtmlHelpers;
    using Common.Services;
    using ExigoService;
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Linq.Expressions;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Optimization;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Shared/EditorTemplates/Checkbox.cshtml")]
    public partial class _Checkbox : System.Web.Mvc.WebViewPage<Boolean>
    {
        public _Checkbox()
        {
        }
        public override void Execute()
        {
            
            #line 2 "..\..\Views\Shared\EditorTemplates\Checkbox.cshtml"
  
    Layout = "~/Views/Shared/EditorTemplates/_FormField.cshtml";
    
    var htmlAttributes = Html.GetEditorHtmlAttributes();

            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n<div");

WriteLiteral(" class=\"checkbox\"");

WriteLiteral(">\r\n    <label");

WriteAttribute("for", Tuple.Create(" for=\"", 189), Tuple.Create("\"", 214)
            
            #line 9 "..\..\Views\Shared\EditorTemplates\Checkbox.cshtml"
, Tuple.Create(Tuple.Create("", 195), Tuple.Create<System.Object, System.Int32>(Html.IdFor(c => c)
            
            #line default
            #line hidden
, 195), false)
);

WriteLiteral(">\r\n");

WriteLiteral("        ");

            
            #line 10 "..\..\Views\Shared\EditorTemplates\Checkbox.cshtml"
   Write(Html.RadioButtonFor(c => c, htmlAttributes));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("        ");

            
            #line 11 "..\..\Views\Shared\EditorTemplates\Checkbox.cshtml"
   Write(Html.DisplayNameFor(c => c));

            
            #line default
            #line hidden
WriteLiteral("\r\n    </label>\r\n</div>");

        }
    }
}
#pragma warning restore 1591
