#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Common.Views.Shared.EditorTemplates
{
    using Common;
    using Common.Helpers;
    using Common.HtmlHelpers;
    using Common.Services;
    using ExigoService;
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Linq.Expressions;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Optimization;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Shared/EditorTemplates/CreditCard.cshtml")]
    public partial class _CreditCard : System.Web.Mvc.WebViewPage<CreditCard>
    {
        public _CreditCard()
        {
        }
        public override void Execute()
        {
            
            #line 2 "..\..\Views\Shared\EditorTemplates\CreditCard.cshtml"
  
    var contextID = Guid.NewGuid().ToString();

    Model.BillingAddress = Model.BillingAddress ?? new Address();
    var defaultCountryCode = (Model.BillingAddress.Country.IsNotNullOrEmpty()) ? Model.BillingAddress.Country : GlobalSettings.Company.Address.Country;
    var defaultRegionCode = (Model.BillingAddress.State.IsNotNullOrEmpty()) ? Model.BillingAddress.State : GlobalSettings.Company.Address.State;

            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n<div");

WriteLiteral(" class=\"view-creditcard\"");

WriteAttribute("id", Tuple.Create(" id=\"", 472), Tuple.Create("\"", 503)
, Tuple.Create(Tuple.Create("", 477), Tuple.Create("view-creditcard-", 477), true)
            
            #line 10 "..\..\Views\Shared\EditorTemplates\CreditCard.cshtml"
, Tuple.Create(Tuple.Create("", 493), Tuple.Create<System.Object, System.Int32>(contextID
            
            #line default
            #line hidden
, 493), false)
);

WriteLiteral(">\r\n\r\n    <input");

WriteLiteral(" type=\"hidden\"");

WriteAttribute("name", Tuple.Create(" name=\"", 533), Tuple.Create("\"", 615)
            
            #line 12 "..\..\Views\Shared\EditorTemplates\CreditCard.cshtml"
, Tuple.Create(Tuple.Create("", 540), Tuple.Create<System.Object, System.Int32>(Html.ViewContext.ViewData.TemplateInfo.HtmlFieldPrefix
            
            #line default
            #line hidden
, 540), false)
, Tuple.Create(Tuple.Create("", 597), Tuple.Create(".PaymentMethodType", 597), true)
);

WriteAttribute("value", Tuple.Create(" value=\"", 616), Tuple.Create("\"", 651)
            
            #line 12 "..\..\Views\Shared\EditorTemplates\CreditCard.cshtml"
                                    , Tuple.Create(Tuple.Create("", 624), Tuple.Create<System.Object, System.Int32>(Model.GetType().ToString()
            
            #line default
            #line hidden
, 624), false)
);

WriteLiteral(" />\r\n");

WriteLiteral("    ");

            
            #line 13 "..\..\Views\Shared\EditorTemplates\CreditCard.cshtml"
Write(Html.HiddenFor(c => c.Type));

            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n    <div");

WriteLiteral(" class=\"row margin-5\"");

WriteLiteral(">\r\n        <div");

WriteLiteral(" class=\"col-sm-6\"");

WriteLiteral(">\r\n            <div");

WriteLiteral(" class=\"form-group\"");

WriteLiteral(">\r\n");

WriteLiteral("                ");

            
            #line 18 "..\..\Views\Shared\EditorTemplates\CreditCard.cshtml"
           Write(Html.EditorFor(c => c.NameOnCard));

            
            #line default
            #line hidden
WriteLiteral("\r\n            </div>\r\n        </div>\r\n        <div");

WriteLiteral(" class=\"col-sm-6\"");

WriteLiteral(">\r\n            <div");

WriteLiteral(" class=\"form-group\"");

WriteLiteral(">\r\n");

WriteLiteral("                ");

            
            #line 23 "..\..\Views\Shared\EditorTemplates\CreditCard.cshtml"
           Write(Html.EditorFor(c => c.CardNumber, new { data_restrict_input = "int" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n            </div>\r\n        </div>\r\n    </div>\r\n\r\n    <div");

WriteLiteral(" class=\"row margin-5\"");

WriteLiteral(">\r\n        <div");

WriteLiteral(" class=\"col-xs-5\"");

WriteLiteral(">\r\n            <div");

WriteLiteral(" class=\"form-group\"");

WriteLiteral(">\r\n");

WriteLiteral("                ");

            
            #line 31 "..\..\Views\Shared\EditorTemplates\CreditCard.cshtml"
           Write(Html.LabelFor(c => c.ExpirationMonth, "Expiration Date", new { @class = "control-label" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("                ");

            
            #line 32 "..\..\Views\Shared\EditorTemplates\CreditCard.cshtml"
           Write(Html.DropDownListFor(c => c.ExpirationMonth,
                    selectList: Html.Months(),
                    htmlAttributes: new
                    {
                        @class = "form-control"
                    }));

            
            #line default
            #line hidden
WriteLiteral("\r\n            </div>\r\n        </div>\r\n        <div");

WriteLiteral(" class=\"col-xs-4\"");

WriteLiteral(">\r\n            <div");

WriteLiteral(" class=\"form-group\"");

WriteLiteral(">\r\n                <label");

WriteAttribute("for", Tuple.Create(" for=\"", 1679), Tuple.Create("\"", 1721)
            
            #line 42 "..\..\Views\Shared\EditorTemplates\CreditCard.cshtml"
, Tuple.Create(Tuple.Create("", 1685), Tuple.Create<System.Object, System.Int32>(Html.NameFor(c => c.ExpirationYear)
            
            #line default
            #line hidden
, 1685), false)
);

WriteLiteral(" class=\"control-label\"");

WriteLiteral(">&nbsp;</label>\r\n");

WriteLiteral("                ");

            
            #line 43 "..\..\Views\Shared\EditorTemplates\CreditCard.cshtml"
           Write(Html.DropDownListFor(c => c.ExpirationYear,
                    selectList: Html.ExpirationYears(),
                    htmlAttributes: new
                    {
                        @class = "form-control"
                    }));

            
            #line default
            #line hidden
WriteLiteral("\r\n            </div>\r\n        </div>\r\n        <div");

WriteLiteral(" class=\"col-xs-3\"");

WriteLiteral(">\r\n            <div");

WriteLiteral(" class=\"form-group\"");

WriteLiteral(">\r\n");

WriteLiteral("                ");

            
            #line 53 "..\..\Views\Shared\EditorTemplates\CreditCard.cshtml"
           Write(Html.EditorFor(c => c.CVV, new { data_restrict_input = "int" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n            </div>\r\n        </div>\r\n    </div>\r\n\r\n    <hr />\r\n\r\n");

WriteLiteral("    ");

            
            #line 60 "..\..\Views\Shared\EditorTemplates\CreditCard.cshtml"
Write(Html.EditorFor(c => Model.BillingAddress, "Address", new { VerifyEnabled = false }));

            
            #line default
            #line hidden
WriteLiteral("\r\n</div>\r\n");

        }
    }
}
#pragma warning restore 1591
