#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Common.Views.Shared.EditorTemplates
{
    using Common;
    using Common.Helpers;
    using Common.HtmlHelpers;
    using Common.Services;
    using ExigoService;
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Linq.Expressions;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Optimization;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Shared/EditorTemplates/DateTime.cshtml")]
    public partial class _DateTime : System.Web.Mvc.WebViewPage<DateTime>
    {
        public _DateTime()
        {
        }
        public override void Execute()
        {
            
            #line 2 "..\..\Views\Shared\EditorTemplates\DateTime.cshtml"
  
    Layout = "~/Views/Shared/EditorTemplates/_FormField.cshtml";

    var contextID = Guid.NewGuid().ToString();
    var htmlAttributes = Html.GetEditorHtmlAttributes(new
    {
        @class = "form-control datetime-" + contextID,
        type   = "text",
        role   = "textbox"
    });

            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n");

            
            #line 14 "..\..\Views\Shared\EditorTemplates\DateTime.cshtml"
Write(Html.TextBoxFor(c => c, htmlAttributes));

            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n<script>\r\n    require([\"kendo\"], function (kendo) {\r\n        $(\'.datetime-");

            
            #line 18 "..\..\Views\Shared\EditorTemplates\DateTime.cshtml"
                Write(contextID);

            
            #line default
            #line hidden
WriteLiteral("\').kendoDateTimePicker({\r\n            culture: \'");

            
            #line 19 "..\..\Views\Shared\EditorTemplates\DateTime.cshtml"
                 Write(UICulture);

            
            #line default
            #line hidden
WriteLiteral("\',\r\n            parseFormats: [\"MM/dd/yyyy h:mm tt\"]\r\n        }).on(\"focus click\"" +
", function () {\r\n            $(this).data(\"kendoDateTimePicker\").open();\r\n      " +
"  });\r\n    });\r\n</script>");

        }
    }
}
#pragma warning restore 1591
