#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Common.Views.Shared.EditorTemplates
{
    using Common;
    using Common.Helpers;
    using Common.HtmlHelpers;
    using Common.Services;
    using ExigoService;
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Linq.Expressions;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Optimization;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Shared/EditorTemplates/NewPassword.cshtml")]
    public partial class _NewPassword : System.Web.Mvc.WebViewPage<String>
    {
        public _NewPassword()
        {
        }
        public override void Execute()
        {
            
            #line 2 "..\..\Views\Shared\EditorTemplates\NewPassword.cshtml"
  
    var contextID = Guid.NewGuid();

    var htmlAttributes = Html.GetEditorHtmlAttributes();

            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n<div");

WriteAttribute("id", Tuple.Create(" id=\"", 125), Tuple.Create("\"", 157)
, Tuple.Create(Tuple.Create("", 130), Tuple.Create("view-newpassword-", 130), true)
            
            #line 8 "..\..\Views\Shared\EditorTemplates\NewPassword.cshtml"
, Tuple.Create(Tuple.Create("", 147), Tuple.Create<System.Object, System.Int32>(contextID
            
            #line default
            #line hidden
, 147), false)
);

WriteLiteral(">\r\n");

WriteLiteral("    ");

            
            #line 9 "..\..\Views\Shared\EditorTemplates\NewPassword.cshtml"
Write(Html.LabelForModel(new { @class = "control-label" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("    ");

            
            #line 10 "..\..\Views\Shared\EditorTemplates\NewPassword.cshtml"
Write(Html.EditorFor(c => c, htmlAttributes));

            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n    <div");

WriteLiteral(" class=\"checkbox\"");

WriteLiteral(">\r\n        <label");

WriteLiteral(" for=\"togglepassword\"");

WriteLiteral(">\r\n            <input");

WriteLiteral(" type=\"checkbox\"");

WriteLiteral(" id=\"togglepassword\"");

WriteLiteral(" data-toggle=\"password\"");

WriteLiteral(" data-id=\"");

            
            #line 14 "..\..\Views\Shared\EditorTemplates\NewPassword.cshtml"
                                                                                  Write(Html.IdFor(c => c));

            
            #line default
            #line hidden
WriteLiteral("\"");

WriteLiteral(" value=\"1\"");

WriteLiteral(" />\r\n            Show my password\r\n        </label>\r\n    </div>\r\n</div>\r\n\r\n\r\n<lin" +
"k");

WriteAttribute("href", Tuple.Create(" href=\"", 532), Tuple.Create("\"", 615)
, Tuple.Create(Tuple.Create("", 539), Tuple.Create<System.Object, System.Int32>(Href("~/Content/scripts/vendor/jquery.passwordstrength/jquery.passwordstrength.css")
, 539), false)
);

WriteLiteral(" rel=\"stylesheet\"");

WriteLiteral(" />\r\n<script>\r\n    require([\"vendor/hideShowPassword\", \"vendor/jquery.passwordstr" +
"ength/jquery.passwordstrength\"], function () {\r\n\r\n        // Settings\r\n        v" +
"ar context = \"#view-newpassword-");

            
            #line 26 "..\..\Views\Shared\EditorTemplates\NewPassword.cshtml"
                                    Write(contextID);

            
            #line default
            #line hidden
WriteLiteral(@""",
            $context = $(context);

        // Show/hide password
        $('[data-toggle=""password""]', $context).on('change', function () {
            $('#{0}'.format($(this).data('id'))).hideShowPassword($(this).prop('checked'));
        });

        $(""#");

            
            #line 34 "..\..\Views\Shared\EditorTemplates\NewPassword.cshtml"
        Write(Html.IdFor(c => c));

            
            #line default
            #line hidden
WriteLiteral("\").passwordValidate();\r\n    });\r\n</script>\r\n");

        }
    }
}
#pragma warning restore 1591
