#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Common.Views.Shared.EditorTemplates
{
    using Common;
    using Common.Helpers;
    using Common.HtmlHelpers;
    using Common.Services;
    using ExigoService;
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Linq.Expressions;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Optimization;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Shared/EditorTemplates/ShippingAddress.cshtml")]
    public partial class _ShippingAddress : System.Web.Mvc.WebViewPage<ShippingAddress>
    {
        public _ShippingAddress()
        {
        }
        public override void Execute()
        {
            
            #line 2 "..\..\Views\Shared\EditorTemplates\ShippingAddress.cshtml"
  
    var contextID = Guid.NewGuid().ToString();

            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n<div");

WriteAttribute("id", Tuple.Create(" id=\"", 85), Tuple.Create("\"", 121)
, Tuple.Create(Tuple.Create("", 90), Tuple.Create("view-shippingaddress-", 90), true)
            
            #line 6 "..\..\Views\Shared\EditorTemplates\ShippingAddress.cshtml"
, Tuple.Create(Tuple.Create("", 111), Tuple.Create<System.Object, System.Int32>(contextID
            
            #line default
            #line hidden
, 111), false)
);

WriteLiteral(">\r\n\r\n    <label");

WriteAttribute("for", Tuple.Create(" for=\"", 137), Tuple.Create("\"", 174)
            
            #line 8 "..\..\Views\Shared\EditorTemplates\ShippingAddress.cshtml"
, Tuple.Create(Tuple.Create("", 143), Tuple.Create<System.Object, System.Int32>(Html.NameFor(c => c.FirstName)
            
            #line default
            #line hidden
, 143), false)
);

WriteLiteral(" class=\"control-label\"");

WriteLiteral(">Full Name</label>\r\n    <div");

WriteLiteral(" class=\"row margin-5\"");

WriteLiteral(">\r\n        <div");

WriteLiteral(" class=\"col-xs-6\"");

WriteLiteral(">\r\n            <div");

WriteLiteral(" class=\"form-group\"");

WriteLiteral(">\r\n");

WriteLiteral("                ");

            
            #line 12 "..\..\Views\Shared\EditorTemplates\ShippingAddress.cshtml"
           Write(Html.EditorFor(c => c.FirstName));

            
            #line default
            #line hidden
WriteLiteral("\r\n            </div>\r\n        </div>\r\n        <div");

WriteLiteral(" class=\"col-xs-6\"");

WriteLiteral(">\r\n            <div");

WriteLiteral(" class=\"form-group\"");

WriteLiteral(">\r\n");

WriteLiteral("                ");

            
            #line 17 "..\..\Views\Shared\EditorTemplates\ShippingAddress.cshtml"
           Write(Html.EditorFor(c => c.LastName));

            
            #line default
            #line hidden
WriteLiteral("\r\n            </div>\r\n        </div>\r\n    </div>\r\n\r\n");

WriteLiteral("    ");

            
            #line 22 "..\..\Views\Shared\EditorTemplates\ShippingAddress.cshtml"
Write(Html.Partial("~/Views/Shared/EditorTemplates/Address.cshtml", Model));

            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n    <div");

WriteLiteral(" class=\"form-group\"");

WriteLiteral(">\r\n");

WriteLiteral("        ");

            
            #line 25 "..\..\Views\Shared\EditorTemplates\ShippingAddress.cshtml"
   Write(Html.LabelFor(c => c.Email, new { @class = "control-label" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("        ");

            
            #line 26 "..\..\Views\Shared\EditorTemplates\ShippingAddress.cshtml"
   Write(Html.EditorFor(c => c.Email));

            
            #line default
            #line hidden
WriteLiteral("\r\n    </div>\r\n\r\n    <div");

WriteLiteral(" class=\"form-group\"");

WriteLiteral(">\r\n");

WriteLiteral("        ");

            
            #line 30 "..\..\Views\Shared\EditorTemplates\ShippingAddress.cshtml"
   Write(Html.LabelFor(c => c.Phone, new { @class = "control-label" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("        ");

            
            #line 31 "..\..\Views\Shared\EditorTemplates\ShippingAddress.cshtml"
   Write(Html.EditorFor(c => c.Phone));

            
            #line default
            #line hidden
WriteLiteral("\r\n    </div>\r\n\r\n</div>\r\n");

        }
    }
}
#pragma warning restore 1591
